#!/bin/bash

case "$1 $2" in
  "dev up")       cd infra/env-dev
                  docker-compose build
                  docker-compose up -d
                  sleep 1
                  docker exec -it envdev_dev_1 /bin/bash
                  ;;

  "dev down")     cd infra/env-dev
                  docker-compose stop
                  docker-compose rm -f
                  ;;

  "build up")     cd infra/env-build
                  docker-compose build
                  docker-compose up
                  docker-compose rm -f
                  cp -rf ../../code/api/dist/livelog ../haskell-deploy
                  docker build -t ecky/livelog ../haskell-deploy
                  ;;

  "build down")   cd infra/env-build
                  docker-compose rm -f
                  ;;

  "pkg up")       cd infra/env-build
                  docker build -t ecky/livelog ../haskell-deploy
                  ;;

  "deploy up")    cd infra/env-deploy
                  docker-compose build
                  docker-compose up -d
                  ;;

  "deploy down")  cd infra/env-deploy
                  docker-compose stop
                  docker-compose rm -f
                  ;;

  *)              echo "Unknown command"
esac