#!/bin/bash
set -e
case "$1 $2" in
  "dev up")       cd infra/env-dev
                  docker-compose build
                  docker-compose up -d
                  ;;

  "dev enter")    docker exec -it envdev_dev_1 /bin/bash
                  ;;

  "dev down")     cd infra/env-dev
                  docker-compose stop
                  docker-compose rm -f
                  ;;

  "build up")     cd infra/env-build
                  docker-compose build
                  docker-compose up
                  docker-compose rm -f
                  rm -rf ../img-deploy/livelog
                  mkdir -p ../img-deploy/livelog/api
                  mkdir -p ../img-deploy/livelog/client
                  cp -rf ../../code/api/dist/livelog ../img-deploy/livelog/api/dist
                  cp -rf ../../code/client/dist ../img-deploy/livelog/client/dist
                  docker build -t ecky/livelog ../img-deploy
                  ;;

  "build local")  code/build.sh
                  ;;

  "build down")   cd infra/env-build
                  docker-compose rm -f
                  ;;

  "deploy up")    cd infra/env-deploy
                  mkdir -p db
                  docker-compose build
                  docker-compose up -d
                  ;;

  "deploy down")  cd infra/env-deploy
                  docker-compose stop
                  docker-compose rm -f
                  ;;

  *)              echo "Unknown command"
esac
