db:
  image: "mysql:5.7"
  env_file: env

apidev:
  build: ../haskell-dev
  env_file: env
  volumes:
    - "../../code/api:/livelog"
  ports:
    - "3000:3000"
  links:
    - db
  command: sleep infinity

clientdev:
  build: ../client-dev
  env_file: env
  volumes: 
    - "../../code/client:/livelog-client"
  ports:
    - "8080:8080"
  command: sleep infinity