db:
  image: "mysql:5.7"
  env_file: env

apidev:
  build: ../haskell-dev
  env_file: env
  volumes:
    - "../../code:/livelog"
  ports:
    - "3000:3000"
  links:
    - db
  command: /livelog/api/build.sh

clientdev:
  build: ../client-dev
  env_file: env
  volumes: 
    - "../../code:/livelog"
  ports:
    - "8080:8080"
  command: "cd /livelog/client/ && npm run build"